/**
 * Build the hub registry: scan content/ (and, from phase 4, federated sources)
 * into a single registry.json that both the catalog site and the CLI consume.
 *
 * Phase 1: local skills only.
 */

import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { validateSkillDir } from "@hmrbot/hub-schema";
import { parseTags } from "@hmrbot/hub-taxonomy";

export interface RegistryEntry {
  slug: string;
  section: "skill" | "prompt" | "software";
  name: string;
  description: string;
  category: string | null;
  tags: string[];
  version: string | null;
  locale: string | null;
  source: string;
  license: string | null;
  path: string | null;
  upstream_url: string | null;
  install: string;
}

export interface Registry {
  _note: string;
  generated_at: string;
  count: number;
  skills: RegistryEntry[];
}

function listSkillDirs(skillsRoot: string): string[] {
  return readdirSync(skillsRoot)
    .filter((n) => !n.startsWith("_") && !n.startsWith("."))
    .map((n) => join(skillsRoot, n))
    .filter((p) => {
      try {
        return statSync(p).isDirectory();
      } catch {
        return false;
      }
    });
}

export interface BuildResult {
  registry: Registry;
  errors: { slug: string; message: string }[];
}

/** Build the registry from the local content/skills directory. */
export function buildRegistry(repoRoot: string): BuildResult {
  const skillsRoot = join(repoRoot, "content", "skills");
  const entries: RegistryEntry[] = [];
  const errors: { slug: string; message: string }[] = [];

  for (const dir of listSkillDirs(skillsRoot)) {
    const res = validateSkillDir(dir);
    if (!res.ok || !res.doc) {
      for (const i of res.issues.filter((x) => x.level === "error")) {
        errors.push({ slug: res.slug, message: i.message });
      }
      continue;
    }
    const fm = res.doc.frontmatter;
    const md = fm.metadata ?? {};
    entries.push({
      slug: res.slug,
      section: "skill",
      name: fm.name,
      description: fm.description.trim(),
      category: (md["hmrbot.category"] as string | undefined) ?? null,
      tags: parseTags(md["hmrbot.tags"] as string | undefined),
      version: (md["hmrbot.version"] as string | undefined) ?? null,
      locale: (md["hmrbot.locale"] as string | undefined) ?? null,
      source: "hmrbot",
      license: fm.license ?? "Apache-2.0",
      path: `content/skills/${res.slug}/`,
      upstream_url: null,
      install: `npx hmrbot skill add ${res.slug}`,
    });
  }

  entries.sort((a, b) => a.slug.localeCompare(b.slug));

  const registry: Registry = {
    _note: "GENERATED by @hmrbot/hub-registry. Do not edit by hand. Run: pnpm build:registry",
    generated_at: new Date().toISOString(),
    count: entries.length,
    skills: entries,
  };

  return { registry, errors };
}
