/**
 * Build the hub registry: scan content/ for first-party skills and, when asked,
 * federate metadata from external repos (sources.yaml). The result is one
 * registry.json that both the catalog site and the CLI consume.
 */

import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { validateSkillDir } from "@hmrbot/hub-schema";
import { parseTags } from "@hmrbot/hub-taxonomy";
import { harvestAll, type Rejection } from "./federation.js";

export interface RegistryEntry {
  slug: string;
  section: "skill" | "prompt" | "software";
  name: string;
  description: string;
  category: string | null;
  tags: string[];
  version: string | null;
  locale: string | null;
  source: string;
  license: string | null;
  path: string | null;
  upstream_url: string | null;
  install: string;
}

export interface Registry {
  _note: string;
  count: number;
  skills: RegistryEntry[];
}

export interface BuildResult {
  registry: Registry;
  errors: { slug: string; message: string }[];
  rejected: Rejection[];
}

function listSkillDirs(skillsRoot: string): string[] {
  return readdirSync(skillsRoot)
    .filter((n) => !n.startsWith("_") && !n.startsWith("."))
    .map((n) => join(skillsRoot, n))
    .filter((p) => {
      try {
        return statSync(p).isDirectory();
      } catch {
        return false;
      }
    });
}

function scanLocal(repoRoot: string): {
  entries: RegistryEntry[];
  errors: { slug: string; message: string }[];
} {
  const skillsRoot = join(repoRoot, "content", "skills");
  const entries: RegistryEntry[] = [];
  const errors: { slug: string; message: string }[] = [];

  for (const dir of listSkillDirs(skillsRoot)) {
    const res = validateSkillDir(dir);
    if (!res.ok || !res.doc) {
      for (const i of res.issues.filter((x) => x.level === "error")) {
        errors.push({ slug: res.slug, message: i.message });
      }
      continue;
    }
    const fm = res.doc.frontmatter;
    const md = fm.metadata ?? {};
    entries.push({
      slug: res.slug,
      section: "skill",
      name: fm.name,
      description: fm.description.trim(),
      category: (md["hmrbot.category"] as string | undefined) ?? null,
      tags: parseTags(md["hmrbot.tags"] as string | undefined),
      version: (md["hmrbot.version"] as string | undefined) ?? null,
      locale: (md["hmrbot.locale"] as string | undefined) ?? null,
      source: "hmrbot",
      license: fm.license ?? "Apache-2.0",
      path: `content/skills/${res.slug}/`,
      upstream_url: null,
      install: `npx hmrbot skill add ${res.slug}`,
    });
  }
  return { entries, errors };
}

const SOURCE_RANK = (s: string) => (s === "hmrbot" ? 0 : 1);

/** Build the registry. `opts.federation` pulls external sources from sources.yaml. */
export async function buildRegistry(
  repoRoot: string,
  opts: { federation?: boolean } = {},
): Promise<BuildResult> {
  const { entries: local, errors } = scanLocal(repoRoot);

  let federated: RegistryEntry[] = [];
  let rejected: Rejection[] = [];
  if (opts.federation) {
    const h = await harvestAll(repoRoot);
    federated = h.entries;
    rejected = h.rejected;
  }

  // first-party wins on slug collisions; then first federated source wins
  const bySlug = new Map<string, RegistryEntry>();
  for (const e of [...local, ...federated]) {
    if (!bySlug.has(e.slug)) bySlug.set(e.slug, e);
  }

  const skills = [...bySlug.values()].sort(
    (a, b) =>
      SOURCE_RANK(a.source) - SOURCE_RANK(b.source) ||
      a.source.localeCompare(b.source) ||
      a.slug.localeCompare(b.slug),
  );

  return {
    registry: {
      _note: "GENERATED by @hmrbot/hub-registry. Do not edit by hand. Run: pnpm build:registry",
      count: skills.length,
      skills,
    },
    errors,
    rejected,
  };
}

export type { Rejection };
