/**
 * Build the hub registry: scan content/ for first-party skills + prompts and,
 * when asked, federate skill metadata from external repos (sources.yaml). One
 * registry.json feeds both the catalog site and the CLI.
 */

import { readdirSync, statSync, existsSync } from "node:fs";
import { join } from "node:path";
import { validateContentDir } from "@hmrbot/hub-schema";
import { parseTags, type Section } from "@hmrbot/hub-taxonomy";
import { harvestAll, type Rejection } from "./federation.js";

export interface RegistryEntry {
  slug: string;
  section: Section;
  name: string;
  description: string;
  category: string | null;
  tags: string[];
  version: string | null;
  locale: string | null;
  source: string;
  license: string | null;
  path: string | null;
  upstream_url: string | null;
  install: string;
}

export interface Registry {
  _note: string;
  count: number;
  skills: RegistryEntry[];
}

export interface BuildResult {
  registry: Registry;
  errors: { slug: string; section: Section; message: string }[];
  rejected: Rejection[];
}

/** content/<section>s/  ->  local sections we ship first-party. */
const LOCAL_SECTIONS: Section[] = ["skill", "prompt"];

function listEntryDirs(root: string): string[] {
  if (!existsSync(root)) return [];
  return readdirSync(root)
    .filter((n) => !n.startsWith("_") && !n.startsWith("."))
    .map((n) => join(root, n))
    .filter((p) => {
      try {
        return statSync(p).isDirectory();
      } catch {
        return false;
      }
    });
}

function scanLocal(repoRoot: string): {
  entries: RegistryEntry[];
  errors: BuildResult["errors"];
} {
  const entries: RegistryEntry[] = [];
  const errors: BuildResult["errors"] = [];

  for (const section of LOCAL_SECTIONS) {
    const root = join(repoRoot, "content", `${section}s`);
    for (const dir of listEntryDirs(root)) {
      const res = validateContentDir(dir, section);
      if (!res.ok || !res.doc) {
        for (const i of res.issues.filter((x) => x.level === "error")) {
          errors.push({ slug: res.slug, section, message: i.message });
        }
        continue;
      }
      const fm = res.doc.frontmatter;
      const md = fm.metadata ?? {};
      entries.push({
        slug: res.slug,
        section,
        name: fm.name,
        description: fm.description.trim(),
        category: (md["hmrbot.category"] as string | undefined) ?? null,
        tags: parseTags(md["hmrbot.tags"] as string | undefined),
        version: (md["hmrbot.version"] as string | undefined) ?? null,
        locale: (md["hmrbot.locale"] as string | undefined) ?? null,
        source: "hmrbot",
        license: fm.license ?? "Apache-2.0",
        path: `content/${section}s/${res.slug}/`,
        upstream_url: null,
        install: `npx hmrbot ${section} add ${res.slug}`,
      });
    }
  }
  return { entries, errors };
}

const SOURCE_RANK = (s: string) => (s === "hmrbot" ? 0 : 1);
const SECTION_RANK: Record<Section, number> = { skill: 0, prompt: 1, software: 2 };

/** Build the registry. `opts.federation` pulls external skill sources. */
export async function buildRegistry(
  repoRoot: string,
  opts: { federation?: boolean } = {},
): Promise<BuildResult> {
  const { entries: local, errors } = scanLocal(repoRoot);

  let federated: RegistryEntry[] = [];
  let rejected: Rejection[] = [];
  if (opts.federation) {
    const h = await harvestAll(repoRoot);
    federated = h.entries;
    rejected = h.rejected;
  }

  // first-party wins on (section, slug) collisions; then first federated source
  const key = (e: RegistryEntry) => `${e.section}/${e.slug}`;
  const byKey = new Map<string, RegistryEntry>();
  for (const e of [...local, ...federated]) {
    if (!byKey.has(key(e))) byKey.set(key(e), e);
  }

  const skills = [...byKey.values()].sort(
    (a, b) =>
      SECTION_RANK[a.section] - SECTION_RANK[b.section] ||
      SOURCE_RANK(a.source) - SOURCE_RANK(b.source) ||
      a.source.localeCompare(b.source) ||
      a.slug.localeCompare(b.slug),
  );

  return {
    registry: {
      _note: "GENERATED by @hmrbot/hub-registry. Do not edit by hand. Run: pnpm build:registry",
      count: skills.length,
      skills,
    },
    errors,
    rejected,
  };
}

export type { Rejection };
